---

# https://github.com/Homebrew/homebrew-completions

# NOTE: The composer & docker completion formulae have been problematic and so
# have been removed. Be cautious about adding them back!

bash_completion_formulae:
  - brew-cask-completion
  - vagrant-completion
