---

# https://docs.travis-ci.com/user/osx-ci-environment

matrix:
  include:
    # macOS 10.12
    - os: osx
      osx_image: xcode8.3
    # macOS 10.11
    - os: osx
      osx_image: xcode7.3

install:
  # Run setup script
  - bash init.sh
  # Debug info
  - pip --version
  - ansible --version

script:
  # Playbook syntax check
  - ansible-playbook macsible.yml --syntax-check
  # Run Ansible playbook:
  # - Skip tasks/roles that we know cause issues in Travis
  # - Skip stage 3/4/5 roles as they don't *really* add much to the test
  - ansible-playbook macsible.yml --skip-tags "no_ci,stage_3,stage_4"
