---

# Override default role variables here.

# atom
# ------------------------------------------------------------------------------

atom_packages:
  - afterglow-monokai-syntax
  - atom-beautify
  - atom-jinja2
  - atom-terminal-tab
  - autoclose-html
  - autocomplete-paths
  - autocomplete-plus
  - double-tag
  - editorconfig
  - emmet
  - file-icons
  - git-plus
  - git-time-machine
  - highlight-line
  - highlight-selected
  - isotope-ui
  - language-ansible
  - language-docker
  - language-nunjucks
  - language-patch
  - linter
  - linter-ansible-syntax
  - linter-jsonlint
  - linter-manager
  - markdown-writer
  - open-recent
  - open-terminal-here
  - php-twig
  - pigments
  - project-manager
  - sort-lines
  - svg-preview
  - tabs-to-spaces
  - todo-show
  - travis-ci-status
  - tree-view-autoresize

# dock items
# ------------------------------------------------------------------------------

dock_apps:
  - Path Finder.app
  - Dash.app
  - Skype.app
  - Slack.app
  - Google Chrome.app
  - Evernote.app
  - Skitch.app
  - Calendar.app
  - PhpStorm.app
  - Atom.app
  - Todoist.app
  - System Preferences.app
  - xScope.app
  - Tower.app
  - Transmit.app
  - Sequel Pro.app
  - VirtualBox.app
  - Terminal.app

# sketch
# ------------------------------------------------------------------------------

sketch_plugin_repos:
  - https://github.com/bomberstudios/sketch-commands.git
  - https://github.com/ddwht/sketch-dynamic-button.git
  - https://github.com/getflourish/Sketch-Style-Inventory.git
  - https://github.com/marcosvidal/Sketch-Notebook
  - https://github.com/ScottSavarie/Clipboard-Fill.git
  - https://github.com/timuric/Content-generator-sketch-plugin.git
  - https://github.com/tylergaw/day-player.git
