---
- name: Mac custom
  hosts: all

# Setup that would be beneficial to have in place ASAP.
- import_playbook: custom-playbooks/mac--first.yml
  tags: "mac__first"

# Essential day-to-day.
- import_playbook: custom-playbooks/mac--day-to-day.yml
  tags: "mac__day_to_day"

# Essential dev.
- import_playbook: custom-playbooks/mac--dev.yml
  tags: "mac__dev"
  
# Project work.
- import_playbook: custom-playbooks/mac--projects.yml
  tags: ["mac__projects", "no_ci"]
    
# Remaining setup.
- import_playbook: custom-playbooks/mac--remaining.yml
  tags: ["mac__remaining", "no_ci"]
  
# Setup that really must be run last.
- import_playbook: custom-playbooks/mac--last.yml
  tags: ["always"]
