---
- name: Mac custom
  hosts: all

- import_playbook: mac-custom--prep.yml
  tags: "prep"

- import_playbook: mac-custom--stage-1.yml
  tags: "stage_1"

- import_playbook: mac-custom--stage-2.yml
  tags: "stage_2"
  
- import_playbook: mac-custom--stage-3.yml
  tags: "stage_3"
    
- import_playbook: mac-custom--stage-4.yml
  tags: "stage_4"
  
- import_playbook: mac-custom--last.yml
  tags: "last"
