---
- name: Mac custom -- stage 2
  hosts: all

  vars_files:
  - config.yml
  - config.local.yml

  roles:

    - { role: vagrant, tags: ["vagrant","stage_2","sudo"] }
    - { role: composer, tags: ["composer","stage_2"] }
    - { role: node_pkgs, tags: ["node_pkgs","stage_2"] }
    - { role: pip_pkgs, tags: ["pip_pkgs","stage_2"] }
    - { role: tower, tags: ["tower","stage_2"] }
    - { role: danbohea.sketch, tags: ["sketch","stage_2","no_ci"] }
    - { brew_pkg_name: "bash-completion", tags: ["bash_completion","stage_2"], role: brew_pkg }
    - { brew_pkg_name: "python", tags: ["python","stage_2"], role: brew_pkg }
    - { brew_pkg_name: "yarn", tags: ["yarn","stage_2"], role: brew_pkg }
    - { brew_pkg_name: "TomAnthony/brews/itermocil", tags: ["itermocil","stage_2"], role: brew_pkg }
    # TODO: Failing builds.
    # - { cask_app_name: "virtualbox", tags: ["virtualbox","stage_2"], role: danbohea.cask-app }
    - { cask_app_name: "dash", tags: ["dash","stage_2"], role: danbohea.cask-app }
    - { cask_app_name: "kaleidoscope", tags: ["kaleidoscope","stage_2"], role: danbohea.cask-app }
    - { cask_app_name: "sequel-pro", tags: ["sequel_pro","stage_2"], role: danbohea.cask-app }
    - { cask_app_name: "transmit", tags: ["transmit","stage_2"], role: danbohea.cask-app }
    - { cask_app_name: "imageoptim", tags: ["imageoptim","stage_2"], role: danbohea.cask-app }
    - { cask_app_name: "xscope", tags: ["xscope","stage_2"], role: danbohea.cask-app }
    - { cask_app_name: "slack", tags: ["slack","stage_2"], role: danbohea.cask-app }
    - { cask_app_name: "browserstacklocal", tags: ["browserstacklocal","stage_2"], role: danbohea.cask-app }
