---

- name: Install Vagrant
  homebrew_cask: name=vagrant state=present
  notify: brew cleanup

- name: Ensure ~/.ssh/ exists
  file:
    path: ~/.ssh
    state: directory

# - name: Check for installed Vagrant plugins
#   command: vagrant plugin list
#   register: vagrant_plugin_list_results

# TODO: Make idempotent
- name: Install Vagrant plugins
  command: vagrant plugin install {{ item }}
  with_items: "{{ vagrant_plugins }}"
