---
- name: Custom - Dev
  hosts: all

  vars_files:
    - config.yml
    - config.local.yml

  roles:

    - { role: vagrant, tags: ["vagrant","sudo"] }
    - { role: composer, tags: "composer" }
    - { role: node, tags: "node" }
    - { role: pip_pkgs, tags: "pip_pkgs" }
    - { role: tower, tags: "tower" }
    - { role: danbohea.sketch, tags: ["sketch","no_ci"] }
    - { brew_pkg_name: "bash-completion", tags: "bash_completion", role: brew_pkg }
    - { brew_pkg_name: "python", tags: "python", role: brew_pkg }
    # TODO: Yarn should depend on the node role really. 
    - { brew_pkg_name: "yarn", brew_pkg_install_options: "without-node", tags: "yarn", role: brew_pkg }
    # TODO: Install this via its own role along with config.
    - { brew_pkg_name: "TomAnthony/brews/itermocil", tags: "itermocil", role: brew_pkg }
    - { brew_pkg_name: "asciinema", tags: "asciinema", role: brew_pkg }
    - { cask_app_name: "figma", tags: "figma", role: danbohea.cask-app }
    # TODO: Failing builds.
    # - { cask_app_name: "virtualbox", tags: "virtualbox", role: danbohea.cask-app }
    - { cask_app_name: "dash", tags: "dash", role: danbohea.cask-app }
    # TODO: Currently fails on install.
    # - { cask_app_name: "kaleidoscope", tags: "kaleidoscope", role: danbohea.cask-app }
    - { cask_app_name: "sequel-pro", tags: "sequel_pro", role: danbohea.cask-app }
    - { cask_app_name: "transmit", tags: "transmit", role: danbohea.cask-app }
    - { cask_app_name: "imageoptim", tags: "imageoptim", role: danbohea.cask-app }
    - { cask_app_name: "xscope", tags: "xscope", role: danbohea.cask-app }
    - { cask_app_name: "slack", tags: "slack", role: danbohea.cask-app }
    - { cask_app_name: "browserstacklocal", tags: "browserstacklocal", role: danbohea.cask-app }
