---
- name: Mac custom
  hosts: all
  connection: local

  tasks:

    # Prep
    # --------------------------------------------------------------------------

    - block:
      - include_role:
          name: danbohea.spelling
        tags: spelling
      tags: prep

    # Stage 1: Essential day-to-day
    # --------------------------------------------------------------------------

    - block:

      - include_role:
          name: danbohea.flux
        tags: flux

      - include_role:
          name: danbohea.cask-app
        vars:
          cask_app_name: "the-unarchiver"
        tags: the_unarchiver
        
      tags: stage_1

    # Last
    # --------------------------------------------------------------------------

    - block:
      - include_role:
          name: danbohea.dock-items
        tags: dock_items
      tags: [last, always]

  post_tasks:

    - debug:
        msg: "Some changes may not take effect until you've restarted your Mac."
      tags: always
