---
- name: Mac setup
  hosts: all
  connection: local

  vars_files:
    - config.yml
    - config.local.yml

  pre_tasks:

    - name: Verify target system is running macOS.
      assert:
        that: ansible_os_family is "Darwin"
        msg: "The target system is not running macOS."
      tags: always

    - name: Verify Ansible meets Macsible's version requirements.
      assert:
        that: "ansible_version.full | version_compare('2.1', '>=')"
        msg: "You must update Ansible to at least 2.1 to use this version of Macsible."
      tags: always

  roles:

    # Prep
    # --------------------------------------------------------------------------

    - { role: danbohea.spelling, tags: ["spelling","prep"] }

    # Stage 1: Essential day-to-day
    # --------------------------------------------------------------------------

    - { role: danbohea.flux, tags: ["flux","stage_1"] }
    - { cask_app_name: "the-unarchiver", tags: ["the_unarchiver","stage_1"], role: danbohea.cask-app }
    - { cask_app_name: "firefox", tags: ["firefox","stage_1"], role: danbohea.cask-app }

    # Last
    # --------------------------------------------------------------------------

    - { role: danbohea.dock-items, tags: ["dock_items","last","always"] }

  post_tasks:

    - debug:
        msg: "Some changes may not take effect until you've restarted your Mac."
      tags: always
